export const en = {
  appName: 'MeetingClock',
  navSetup: 'Timer',
  navHistory: 'History',
  navSettings: 'Settings',
  navPaywall: 'Plus',
  navPrivacy: 'Privacy',
  setupTitle: 'MeetingClock',
  setupSubtitle: 'Start a room-readable meeting timer in seconds.',
  durationLabel: 'Duration',
  customDurationLabel: 'Custom minutes',
  customDurationPlaceholder: 'Minutes',
  warningLabel: 'Warning threshold',
  criticalLabel: 'Critical threshold',
  thresholdHelp: 'Thresholds are minutes before time runs out.',
  countdown: 'Count down',
  countup: 'Count up',
  startTimer: 'Start timer',
  presetsLabel: 'Presets',
  minutesShort: '{{count}} min',
  adsMockLabel: 'Ad placement',
  adsMockBody: 'Ads appear here in a development build and never during the active timer.',
  plusActive: 'Plus active',
  freePlan: 'Free plan',
  sessionRunning: 'Running',
  sessionPaused: 'Paused',
  sessionComplete: 'Complete',
  normalState: 'Normal',
  warningState: 'Warning',
  criticalState: 'Critical',
  overtimeState: 'Overtime',
  remainingLabel: 'Remaining',
  elapsedLabel: 'Elapsed',
  overtimeLabel: 'Overtime',
  pause: 'Pause',
  resume: 'Resume',
  restart: 'Restart',
  quit: 'Quit',
  reset: 'Reset',
  complete: 'Complete',
  backToSetup: 'Back to setup',
  noActiveSessionTitle: 'No active timer',
  noActiveSessionBody: 'Start a timer from the setup screen.',
  historyTitle: 'Session history',
  historyTotalFocusToday: 'Total focus today',
  historyAllTime: 'All Time',
  historyQuick15: '15m Quick',
  historyClientMeeting: 'Client Meeting',
  historyEmptyTitle: 'No saved sessions yet',
  historyEmptyBody: 'Completed and reset sessions will appear here.',
  historyCompleted: 'Completed',
  historyReset: 'Reset',
  settingsTitle: 'Settings',
  languageLabel: 'Language',
  automatic: 'Automatic',
  english: 'English',
  spanish: 'Español',
  modeLabel: 'Default mode',
  mockPlusLabel: 'Development Plus override',
  mockPlusHelp: 'Mocks Plus locally without RevenueCat.',
  plusMonthly: 'Monthly Plus',
  plusYearly: 'Yearly Plus',
  plusLifetime: 'Lifetime ad-free',
  plusBadge: 'PRO',
  plusBestValue: 'Best value',
  plusMonthlySubtitle: 'Flexible monthly access',
  plusYearlySubtitle: 'Save with one annual payment',
  plusLifetimeSubtitle: 'One payment, no recurring subscription',
  plusFeatureNoAds: 'No ads outside the timer',
  plusFeaturePresets: 'Unlimited saved presets',
  plusFeatureThemes: 'Presentation themes',
  plusFeatureHistory: 'Extended local history',
  plusMockPrice: 'Mock purchase',
  plusUnavailablePrice: 'Unavailable',
  purchaseButton: 'Choose {{plan}}',
  purchaseShortButton: 'Choose',
  restorePurchases: 'Restore purchases',
  purchaseLoading: 'Contacting store...',
  purchasePurchased: 'Plus is active.',
  purchaseRestored: 'Purchases restored. Plus is active.',
  purchaseCancelled: 'Purchase cancelled.',
  purchaseUnavailable: 'This product is not available yet. Check RevenueCat and App Store Connect setup.',
  purchaseManagementOpened: 'Opening subscription management...',
  purchaseManagementUnavailable: 'Subscription management is not available for this test purchase.',
  purchaseStatusRefreshed: 'Subscription status refreshed.',
  purchaseError: 'Purchase failed. Try again in a moment.',
  manageSubscription: 'Manage or cancel subscription',
  refreshSubscriptionStatus: 'Refresh status',
  subscriptionRenews: 'Renews automatically.',
  subscriptionCancelsAt: 'Canceled. Plus stays active until {{date}}.',
  subscriptionActiveLifetime: 'Lifetime access is active.',
  purchasesMockMode: 'Development mode is using local mock purchases.',
  purchasesRevenueCatMode: 'RevenueCat is enabled for this build.',
  paywallTitle: 'MeetingClock Plus',
  paywallBody: 'Plus will remove ads, unlock unlimited presets, add presentation themes, and keep extended history.',
  paywallMockNote: 'Use the Plus options below. In development mock mode, purchases are simulated locally.',
  privacyTitle: 'Privacy',
  privacyBody: 'MeetingClock stores settings, language preference, Plus state, and session history on this device. No login, custom backend, or analytics are configured in this build.',
  privacyAds: 'Ads may appear outside the active timer when AdMob is configured. Ad providers may process device and ad-related data.',
  privacyPurchases: 'Purchases are managed through the App Store and RevenueCat when real purchases are enabled. Development builds can use a local mock entitlement.',
  contact: 'Contact: luegodev',
  loading: 'Loading MeetingClock',
  errorTitle: 'Something went wrong',
} as const;
