export const en = {
  appName: 'MeetingClock',
  navSetup: 'Timer',
  navHistory: 'History',
  navSettings: 'Settings',
  navPaywall: 'Plus',
  navPrivacy: 'Privacy',
  setupTitle: 'MeetingClock',
  setupSubtitle: 'Start a room-readable meeting timer in seconds.',
  durationLabel: 'Duration',
  customDurationLabel: 'Custom minutes',
  customDurationPlaceholder: 'Minutes',
  warningLabel: 'Warning threshold',
  criticalLabel: 'Critical threshold',
  thresholdHelp: 'Thresholds are minutes before time runs out.',
  countdown: 'Count down',
  countup: 'Count up',
  startTimer: 'Start timer',
  presetsLabel: 'Presets',
  minutesShort: '{{count}} min',
  adsMockLabel: 'Ad placement',
  adsMockBody: 'Ads appear here in a development build and never during the active timer.',
  plusActive: 'Plus active',
  freePlan: 'Free plan',
  sessionRunning: 'Running',
  sessionPaused: 'Paused',
  sessionComplete: 'Complete',
  normalState: 'Normal',
  warningState: 'Warning',
  criticalState: 'Critical',
  overtimeState: 'Overtime',
  remainingLabel: 'Remaining',
  elapsedLabel: 'Elapsed',
  overtimeLabel: 'Overtime',
  pause: 'Pause',
  resume: 'Resume',
  restart: 'Restart',
  quit: 'Quit',
  reset: 'Reset',
  complete: 'Complete',
  backToSetup: 'Back to setup',
  noActiveSessionTitle: 'No active timer',
  noActiveSessionBody: 'Start a timer from the setup screen.',
  historyTitle: 'Session history',
  historyTotalFocusToday: 'Total focus today',
  historyAllTime: 'All Time',
  historyQuick15: '15m Quick',
  historyClientMeeting: 'Client Meeting',
  historyEmptyTitle: 'No saved sessions yet',
  historyEmptyBody: 'Completed and reset sessions will appear here.',
  historyCompleted: 'Completed',
  historyReset: 'Reset',
  settingsTitle: 'Settings',
  languageLabel: 'Language',
  automatic: 'Automatic',
  english: 'English',
  spanish: 'Español',
  modeLabel: 'Default mode',
  mockPlusLabel: 'Development Plus override',
  mockPlusHelp: 'Mocks Plus locally without RevenueCat.',
  paywallTitle: 'MeetingClock Plus',
  paywallBody: 'Plus will remove ads, unlock unlimited presets, add presentation themes, and keep extended history.',
  paywallMockNote: 'Purchases are not configured yet. Use the development override in Settings.',
  privacyTitle: 'Privacy',
  privacyBody: 'MeetingClock stores settings, language preference, mock Plus state, and session history on this device. No login, backend, analytics, or real purchases are configured in this build.',
  privacyAds: 'Ads may appear outside the active timer when AdMob is configured. Ad providers may process device and ad-related data.',
  privacyPurchases: 'Future purchases will be managed through the app store and RevenueCat. This build uses only a local mock entitlement.',
  contact: 'Contact: luegodev',
  loading: 'Loading MeetingClock',
  errorTitle: 'Something went wrong',
} as const;
