import type { en } from './en';

export const es = {
  appName: 'MeetingClock',
  navSetup: 'Temporizador',
  navHistory: 'Historial',
  navSettings: 'Ajustes',
  navPaywall: 'Plus',
  navPrivacy: 'Privacidad',
  setupTitle: 'MeetingClock',
  setupSubtitle: 'Inicia en segundos un temporizador visible para toda la sala.',
  durationLabel: 'Duración',
  customDurationLabel: 'Minutos personalizados',
  customDurationPlaceholder: 'Minutos',
  warningLabel: 'Umbral de advertencia',
  criticalLabel: 'Umbral crítico',
  thresholdHelp: 'Los umbrales son minutos antes de que se acabe el tiempo.',
  countdown: 'Cuenta regresiva',
  countup: 'Cuenta progresiva',
  startTimer: 'Iniciar temporizador',
  presetsLabel: 'Preajustes',
  minutesShort: '{{count}} min',
  adsMockLabel: 'Espacio de anuncio',
  adsMockBody: 'Los anuncios aparecen aquí en una versión de desarrollo y nunca durante el temporizador activo.',
  plusActive: 'Plus activo',
  freePlan: 'Plan gratis',
  sessionRunning: 'En marcha',
  sessionPaused: 'Pausado',
  sessionComplete: 'Completo',
  normalState: 'Normal',
  warningState: 'Advertencia',
  criticalState: 'Crítico',
  overtimeState: 'Tiempo extra',
  remainingLabel: 'Restante',
  elapsedLabel: 'Transcurrido',
  overtimeLabel: 'Tiempo extra',
  pause: 'Pausar',
  resume: 'Reanudar',
  restart: 'Reiniciar',
  quit: 'Salir',
  reset: 'Reiniciar',
  complete: 'Completar',
  backToSetup: 'Volver al inicio',
  noActiveSessionTitle: 'No hay temporizador activo',
  noActiveSessionBody: 'Inicia un temporizador desde la pantalla principal.',
  historyTitle: 'Historial de sesiones',
  historyTotalFocusToday: 'Concentración total hoy',
  historyAllTime: 'Todo',
  historyQuick15: '15m rápido',
  historyClientMeeting: 'Reunión con cliente',
  historyEmptyTitle: 'Aún no hay sesiones guardadas',
  historyEmptyBody: 'Las sesiones completadas y reiniciadas aparecerán aquí.',
  historyCompleted: 'Completada',
  historyReset: 'Reiniciada',
  settingsTitle: 'Ajustes',
  languageLabel: 'Idioma',
  automatic: 'Automático',
  english: 'English',
  spanish: 'Español',
  modeLabel: 'Modo predeterminado',
  mockPlusLabel: 'Activación Plus de desarrollo',
  mockPlusHelp: 'Simula Plus localmente sin RevenueCat.',
  plusMonthly: 'Plus mensual',
  plusYearly: 'Plus anual',
  plusLifetime: 'Sin anuncios de por vida',
  plusMockPrice: 'Compra simulada',
  plusUnavailablePrice: 'No disponible',
  purchaseButton: 'Elegir {{plan}}',
  restorePurchases: 'Restaurar compras',
  purchaseLoading: 'Contactando la tienda...',
  purchasePurchased: 'Plus está activo.',
  purchaseRestored: 'Compras restauradas. Plus está activo.',
  purchaseCancelled: 'Compra cancelada.',
  purchaseUnavailable: 'Este producto aún no está disponible. Revisa RevenueCat y App Store Connect.',
  purchaseError: 'La compra falló. Inténtalo de nuevo en un momento.',
  purchasesMockMode: 'El modo de desarrollo usa compras simuladas locales.',
  purchasesRevenueCatMode: 'RevenueCat está activo en esta versión.',
  paywallTitle: 'MeetingClock Plus',
  paywallBody: 'Plus quitará anuncios, desbloqueará preajustes ilimitados, agregará temas de presentación y conservará más historial.',
  paywallMockNote: 'Usa las opciones Plus de abajo. En modo de desarrollo, las compras se simulan localmente.',
  privacyTitle: 'Privacidad',
  privacyBody: 'MeetingClock guarda ajustes, preferencia de idioma, estado Plus e historial de sesiones en este dispositivo. Esta versión no usa cuentas, backend propio ni analíticas.',
  privacyAds: 'Los anuncios pueden aparecer fuera del temporizador activo cuando AdMob esté configurado. Los proveedores de anuncios pueden procesar datos del dispositivo y de anuncios.',
  privacyPurchases: 'Las compras se gestionan mediante App Store y RevenueCat cuando las compras reales están activas. Las versiones de desarrollo pueden usar una autorización local simulada.',
  contact: 'Contacto: luegodev',
  loading: 'Cargando MeetingClock',
  errorTitle: 'Algo salió mal',
} as const satisfies Record<keyof typeof en, string>;
